INSERT INTO Food (name, food_category, is_organic, is_vegan, is_vegetarian, brand, price, is_lbs)
VALUES ('Milk', 'dairy', TRUE, FALSE, TRUE, 'Horizon', 4.65, FALSE),
VALUES ('Lemon', 'fruit', TRUE, TRUE, TRUE, NULL, 2.99, TRUE),
VALUES ('White Hamburger Bun', 'bread', TRUE, FALSE, TRUE, NULL, 2.99, FALSE),
VALUES ('Meatless Orange Chicken', 'frozen', TRUE, FALSE, TRUE, 'Gardein', 4.49), FALSE,
VALUES ('Tortilla Chips', 'snack', TRUE, FALSE, TRUE, 'Cabo', 2.99, FALSE),
VALUES ('White Hamburger Bun', 'vegetable', TRUE, FALSE, TRUE, NULL, 2.99, FALSE),
VALUES ('Shoe String Potatoes', 'frozen', TRUE, FALSE, TRUE, '365', 2.99, FALSE),
VALUES ('White Hamburger Bun', 'vegetable', TRUE, FALSE, TRUE, NULL, 2.99, FALSE),
VALUES ('Whipped Cream', 'dairy', FALSE, FALSE, TRUE, 'Natural by Nature', 5.29, FALSE),
VALUES ('Brown Mushrooms', 'vegetable', TRUE, TRUE, TRUE, 'All Seasons', 3.29, FALSE),
VALUES ('Smart Bacon', 'meat', TRUE, FALSE, TRUE, NULL, 2.99, FALSE),
VALUES ('Vine Tomatoes', 'vegetable', TRUE, TRUE, TRUE, NULL, 2.61, TRUE),
VALUES ('Smart Water 50.7 FL OZ', 'beverage', TRUE, TRUE, TRUE, 'Glacéau', 2.59, FALSE),
VALUES ('Unsweetened Apple Sauce', 'beverage', TRUE, FALSE, TRUE, '365', 3.49, FALSE),
VALUES ('Banana', 'fruit', TRUE, TRUE, TRUE, NULL 0.49, TRUE),
VALUES ('Cocoa Rice', 'cereal', TRUE, TRUE, TRUE, 'Glacéau', 2.59, FALSE),
VALUES ('Meatless Turkey Cutlet', 'frozen', TRUE, FALSE, TRUE, 'Gardein', 4.99, FALSE),
VALUES ('7 Grain Chicken Tenders', 'frozen', TRUE, FALSE, TRUE, 'Gardein', 4.99, FALSE),
VALUES ('Large NON GMO Grown Egg', 'egg', FALSE, FALSE, TRUE, NULL, 2.99, FALSE),
